# 25th

# Numpy

# NumPy is the fundamental package for scientific computing in Python.
It is a Python library that provides a multidimensional array object, various derived objects
(such as masked arrays and matrices), and an assortment of routines for fast operations on
arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete
Fourier transforms, basic linear algebra, basic statistical operations, random simulation and
much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types 

# Create Numpy

In [2]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
np.array([2,4,6,22,66,78]) # 1D

array([ 2,  4,  6, 22, 66, 78])

In [4]:
 a = np.array([2,4,56,422,32,1]) # Vector
print(a)

[  2   4  56 422  32   1]


In [5]:
type(a)

numpy.ndarray

In [6]:
# 2D Array(Matrix)

In [7]:
new = np.array([[1, 2, 4, 6, 8,],[4, 5, 9, 10, 4]])
new

array([[ 1,  2,  4,  6,  8],
       [ 4,  5,  9, 10,  4]])

In [8]:
# 3D -- Tensor



In [9]:
np.array ( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])


array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [10]:
my_list = [1, 2, 3, 5, 8]
my_list

[1, 2, 3, 5, 8]

In [11]:
type(my_list)

list

In [12]:
# Convert list to array

In [13]:
arr = np.array(my_list)
arr

array([1, 2, 3, 5, 8])

In [14]:
type(arr)

numpy.ndarray

# Dtype
The desired data-type for the array. If not given, then the type willbe determined as the
minimum type required to hold the objects in thesequence.

In [15]:
np.array([1, 2, 5, 6, 8] , dtype=float)

array([1., 2., 5., 6., 8.])

In [16]:
np.array([10, 20, 30, 40, 50, 0] , dtype=bool) # 

array([ True,  True,  True,  True,  True, False])

In [17]:
np.array([10, 20, 30] , dtype=complex)

array([10.+0.j, 20.+0.j, 30.+0.j])

# Arange
arange can be called with a varying number of positional arguments

In [18]:
np.arange(5) # It always work (n-1) it will print(0 - 4) number

array([0, 1, 2, 3, 4])

In [19]:
np.arange(10 , 20) # print(10 - 19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(10 , 20, 4) # First starting number , second last number and third is step counting it will print(10 , 14,18)

array([10, 14, 18])

In [21]:
np.arange(20, 40, 5)

array([20, 25, 30, 35])

In [22]:
np.arange(1, 25, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# ones & Zeros
you can initialize the values and create values . ex: in deep learning weight shape

In [23]:
# np.ones and np.zeros


In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros(5 , dtype=int) # Convert float to integer

array([0, 0, 0, 0, 0])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

In [28]:
np.zeros((3,4)) # 3 rows and 4 column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((3,4), dtype=int) # 3 rows and 4 column

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
np.ones((3,4)) # 3 rows and 4 column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.ones((3,4),dtype=int) # 3 rows and 4 column

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
#  Another Type ---> random()

In [33]:
rand(4)

NameError: name 'rand' is not defined

In [34]:
np.random.rand(4) # It will generate random number

array([0.09159712, 0.2270065 , 0.72018972, 0.12425724])

In [35]:
np.random.rand(2,2)

array([[0.747981  , 0.27212539],
       [0.21065991, 0.55638372]])

In [36]:
np.random.randint(3) # It will generate random integer number(0 - 2)

0

In [37]:
np.random.randint(10,18)  # It will generate random integer number(10 - 17) it work (n-1) apporach

14

In [38]:
np.random.randint(1,5,3) # It will generate 3 random number (1 - 4)

array([1, 4, 2], dtype=int32)

In [3]:
np.random.randint( 1, 5, 4) # It will generate 4 random number (1 - 4)

array([1, 4, 2, 1], dtype=int32)

In [4]:
np.random.randint(5,2,3)

ValueError: low >= high

In [41]:
np.random.randint(-5,2,3)

array([-3, -5, -5], dtype=int32)

In [42]:
np.random.randint(10,40, (10,10)) # it will generate random integer number(10-39) then 10 rows and 10 columns

array([[17, 20, 36, 26, 12, 26, 10, 24, 33, 20],
       [38, 26, 17, 14, 37, 12, 36, 18, 35, 11],
       [19, 23, 39, 18, 14, 23, 18, 30, 30, 24],
       [35, 31, 26, 34, 29, 20, 23, 27, 28, 13],
       [37, 24, 25, 25, 25, 12, 34, 38, 32, 20],
       [17, 30, 18, 11, 31, 13, 39, 32, 19, 29],
       [31, 24, 12, 36, 33, 39, 13, 38, 33, 15],
       [36, 25, 13, 30, 23, 24, 12, 14, 11, 29],
       [16, 28, 13, 22, 16, 26, 13, 31, 38, 28],
       [24, 37, 39, 19, 11, 25, 15, 37, 11, 12]], dtype=int32)

In [43]:
arr = np.random.randint(10,40,(10,10)) # it will generate random integer number(10-39) then 10 rows and 10 columns and dtype will be not print
print(arr)

[[12 33 10 35 23 11 29 20 17 35]
 [22 29 16 36 12 15 32 17 15 19]
 [14 25 22 11 31 14 14 34 18 33]
 [15 14 39 10 25 35 33 27 33 34]
 [17 31 26 39 22 27 22 19 25 21]
 [13 26 16 30 30 36 15 15 26 18]
 [35 26 10 31 17 24 31 31 18 39]
 [21 31 32 15 24 29 18 29 19 27]
 [36 38 21 38 17 30 23 15 19 19]
 [23 37 37 31 29 11 25 25 28 11]]


In [44]:
len(arr) # Bydefault it will be print only row

10

# Shape
gives each item consist of no.of rows and np.of column

In [45]:


arr.shape

(10, 10)

In [46]:
id(arr)

1590794222736

 # reshape

In [47]:


np.arange(1, 13).reshape(3,4) # It will convert 3 rows and 4 column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [49]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:

np.arange(1,15).reshape(5,6) # It gives value error

ValueError: cannot reshape array of size 14 into shape (5,6)

In [51]:
np.arange(1,12).reshape(1,11) # It will convert 1 rows and 11 columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [52]:
np.arange(1,12).reshape(11,1) # it will convert 11 rows and 1 columns

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

# Linspace
It is also called as Linearly space , Linearly separable,in a given range at equal distance it
creates points.


In [53]:
np.linspace(-10, 10, 10) 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [54]:

np.linspace(-2, 12, 6 )

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [55]:
np.linspace(-2,  12, 6 , dtype = int)

array([-2,  0,  3,  6,  9, 12])

# Identity
identity matrix is that diagonal items will be ones and evrything will be zeros

In [56]:
# creating the indentity matrix
np.identity(3) # Bydefault it create float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.identity(4, dtype=int) # convert float to integer

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Array Attributes Function

In [58]:
a1 = np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a2 = np.arange(12, dtype=float).reshape(3,4)  # Matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [60]:
a3 = np.arange(8).reshape(2, 2, 2) # 3D --> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim
To findout given arrays number of dimensions

In [61]:
a1.ndim

1

In [62]:
a2.ndim

2

In [63]:
a3.ndim

3

In [64]:
a3.ndim

3

# Size
gives number of items

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
a3.size # it has 8 items . like shape :2,2,2 = 8


8

In [67]:
a2.size

12

In [68]:
a1.size

10

# item size
Memory occupied by the item

In [ ]:
a1

In [69]:
a1.itemsize # bytes

8

In [70]:
a2.itemsize


8

In [71]:
a3.itemsize

8

# dtype
gives data type of the item

In [72]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Data items

In [73]:
# astype
x = np.array([33, 22, 2.5]) 
x

array([33. , 22. ,  2.5])

In [74]:
x.astype(int)

array([33, 22,  2])

In [75]:
x.astype(str)

array(['33.0', '22.0', '2.5'], dtype='<U32')

In [76]:
x.astype(bool)

array([ True,  True,  True])

In [77]:
x.astype(complex)

array([33. +0.j, 22. +0.j,  2.5+0.j])

# Array Operations

In [78]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [79]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operations
Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication
on each element of a Numpy array.


In [81]:
# Additions  # we can add item wise
z1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [82]:

# Substraction
z1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [83]:
# Multiplications
z1 * 3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [84]:
# Power
z1 ** 2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [85]:
# Modulo
z1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# Relatonal Operators
The relational operators are also known as comparison operators, their main function is to
return either a true or false based on the value of operands

In [86]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
z2 > 2  # if 2 is greater than evrythig gives True


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector Operation
We can apply both on numpy array

In [89]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [91]:
# Arthemetic
z1 + z2  # both numpy array Shape is same , we can add item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [92]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [93]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [94]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [95]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[33., 69., 77.],
       [39., 61., 31.],
       [23., 10.,  7.]])

In [96]:
# Max
np.max(k1)


np.float64(77.0)

In [97]:
# Min
np.min(k1)

np.float64(7.0)

In [98]:
# Sum
np.sum(k1)

np.float64(350.0)

In [99]:
# prod ----> Multiplication
np.prod(k1)

np.float64(20817844857810.0)

In [100]:
# if we want maximum of every row
np.max(k1, axis=1)

array([77., 61., 23.])

In [101]:
#  maximum of every column
np.max(k1 , axis = 0)

array([39., 69., 77.])

In [102]:
# Product of every column
np.prod(k1 , axis = 0)

array([29601., 42090., 16709.])

# Statistics related fuctions


In [ ]:

k1

# Mean
 


In [ ]:
# Mean is the average of a set of numbers
# sum of all values/ number of value

In [103]:
np.mean(k1)

np.float64(38.888888888888886)

In [104]:
# mean of every column
np.mean(k1, axis=0)

array([31.66666667, 46.66666667, 38.33333333])

# Median

In [105]:
# Definition: Median is the middle value when all numbers are arranged in order.
# Steps:
# Sort the numbers.
# If count is odd → middle number is median.
# If count is even → average of the two middle numbers.
# Example:
# Numbers = [10, 20, 30, 40]
# Sorted = [10, 20, 30, 40]
# Middle two = 20 and 30 → Median = (20 + 30) ÷ 2 = 25'''


In [106]:
np.median(k1)

np.float64(33.0)

In [107]:
np.median(k1, axis=0)

array([33., 61., 31.])

In [108]:
# Standard deviation


In [109]:
np.std(k1)

np.float64(23.68517794573196)

In [110]:
np.std(k1 , axis=0)

array([ 6.59966329, 26.13214283, 29.04402788])

In [111]:
# variance
np.var(k1)

np.float64(560.9876543209876)

# Trignometry Functions


In [112]:
np.sin(k1)

array([[ 0.99991186, -0.11478481,  0.99952016],
       [ 0.96379539, -0.96611777, -0.40403765],
       [-0.8462204 , -0.54402111,  0.6569866 ]])

In [113]:
np.cos(k1)

array([[-0.01327675,  0.99339038, -0.03097503],
       [ 0.26664293, -0.25810164,  0.91474236],
       [-0.53283302, -0.83907153,  0.75390225]])

In [114]:
np.tan(k1)

array([[-75.3130148 ,  -0.11554855, -32.26857578],
       [  3.61455441,   3.74316794,  -0.44169557],
       [  1.58815308,   0.64836083,   0.87144798]])

# dot product
The numpy module of Python provides a function to perform the dot product of two arrays.

In [115]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)

In [116]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
np.dot(s2,s3) # dot product of s2 ,  1st rows multiply 1st columns


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# Log and Exponents

In [119]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round / floor /ceil

# Round
The numpy.round() function rounds the elements of an array to the nearest integer or to the
specified number of decimals

In [120]:
# Round to the nearest integer
arr = np.array([1.2, 2.7, 3.5, 4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [121]:
# Round to two decimals
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)


[1.23 2.57 3.89]


In [122]:
#randomly
np.round(np.random.random((2,3))*100)

array([[61., 51., 20.],
       [ 3.,  7.,  4.]])

# Floor
The numpy.floor() function returns the largest integer less than or equal to each element of an
array.


In [123]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [124]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[31., 53., 74.],
       [49., 89., 19.]])

# Ceil
The numpy.ceil() function returns the smallest integer greater than or equal to each element of
an array

In [125]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)


[2. 3. 4. 5.]


In [126]:

np.ceil(np.random.random((2,3))*100) # gives highest integer 

array([[  2., 100.,  52.],
       [ 27.,  39.,  76.]])

# Indexing and slicing

In [127]:


ri = np.random.randint(10,40,(10,10))
ri

array([[10, 39, 12, 30, 28, 21, 23, 29, 28, 27],
       [27, 30, 25, 27, 13, 14, 11, 11, 16, 18],
       [32, 27, 35, 37, 28, 22, 38, 30, 20, 13],
       [11, 14, 21, 22, 19, 17, 19, 26, 25, 38],
       [32, 22, 28, 23, 32, 30, 20, 32, 28, 26],
       [19, 37, 34, 31, 26, 26, 34, 21, 24, 21],
       [27, 38, 14, 11, 13, 10, 19, 16, 17, 24],
       [38, 10, 31, 25, 38, 29, 37, 33, 29, 20],
       [34, 39, 32, 22, 13, 37, 27, 17, 12, 20],
       [18, 35, 30, 38, 26, 15, 20, 19, 35, 14]], dtype=int32)

In [128]:
ri[0] # It alway start 0

array([10, 39, 12, 30, 28, 21, 23, 29, 28, 27], dtype=int32)

In [129]:


ri[3]

array([11, 14, 21, 22, 19, 17, 19, 26, 25, 38], dtype=int32)

In [130]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [131]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Indexing on 1D array


In [134]:
p1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
# Fetching last item
p1[-1]

np.int64(9)

In [136]:
p1[5]

np.int64(5)

In [137]:
# Fetching 1st item
p1[0]

np.int64(0)

# indexing on 2D array


In [138]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
# fetching desired element : 6
p2[1,2] # here 1 = row(second) , 2= column(third) , becoz it starts from zero

np.int64(6)

In [140]:
p2[1,1] # row = 1 , column = 1

np.int64(5)

In [141]:
p2[2,2] # row = 2 and column = 2

np.int64(10)

In [142]:
# fetching desired element :
p2[1,0] # row =1 , column =0

np.int64(4)

# indexing on 3D ( Tensors)


In [143]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [144]:
# fetching desired element : 5
p3[1,0,1] # EXPLANATION :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is
           # 5 is in second matrix which is 1 .and 1 row so 0 and second column so 1

np.int64(5)

In [145]:
# fetching desired element : 6
p3[1,1,0] # EXPLANATION : Here first we take because our desired is 6, is in second matrix which is 1 .
           # and second row so 1 and first column so 0

np.int64(6)

In [146]:
# fetching desired element : 0
p3[0,0,0]
#Here first we take 0 because our desired is 0, is in first matrix which is 0 . and 1 row so 0 and
# first column so 0


np.int64(0)

# Slicing
Fetching multiple items


In [147]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:

p1[:] # It will be print all items

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
p1[:-1] # It will be print reverse of all items

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [150]:
# fetching desired elements are : 2,3,4
p1[2:5]

array([2, 3, 4])

In [151]:
# Alternate (same as python)
p1[2:5:2]


array([2, 4])

# Slicing on 2D


In [152]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
# Fetch total first row
p2[0,:]

array([0, 1, 2, 3])

In [154]:
# fetching total second column
p2[:,2]

array([ 2,  6, 10])

In [155]:
# fetching total third column
p2[:,3]

array([ 3,  7, 11])

In [156]:
p2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [157]:
ri

array([[10, 39, 12, 30, 28, 21, 23, 29, 28, 27],
       [27, 30, 25, 27, 13, 14, 11, 11, 16, 18],
       [32, 27, 35, 37, 28, 22, 38, 30, 20, 13],
       [11, 14, 21, 22, 19, 17, 19, 26, 25, 38],
       [32, 22, 28, 23, 32, 30, 20, 32, 28, 26],
       [19, 37, 34, 31, 26, 26, 34, 21, 24, 21],
       [27, 38, 14, 11, 13, 10, 19, 16, 17, 24],
       [38, 10, 31, 25, 38, 29, 37, 33, 29, 20],
       [34, 39, 32, 22, 13, 37, 27, 17, 12, 20],
       [18, 35, 30, 38, 26, 15, 20, 19, 35, 14]], dtype=int32)

In [158]:
ri[3:8]

array([[11, 14, 21, 22, 19, 17, 19, 26, 25, 38],
       [32, 22, 28, 23, 32, 30, 20, 32, 28, 26],
       [19, 37, 34, 31, 26, 26, 34, 21, 24, 21],
       [27, 38, 14, 11, 13, 10, 19, 16, 17, 24],
       [38, 10, 31, 25, 38, 29, 37, 33, 29, 20]], dtype=int32)

In [159]:
ri[2:9:3]

array([[32, 27, 35, 37, 28, 22, 38, 30, 20, 13],
       [19, 37, 34, 31, 26, 26, 34, 21, 24, 21],
       [34, 39, 32, 22, 13, 37, 27, 17, 12, 20]], dtype=int32)

In [160]:
print(ri[3,8]) # rows = 3 and column = 8

25


In [161]:
print(ri[9,9]) # row = 9 &  column = 9

14


In [162]:
print(ri[-2,-4]) # row = -2 & column = -4 

27


In [163]:
print(ri[-5])

[19 37 34 31 26 26 34 21 24 21]


In [164]:
print(ri[-5,-3]) # fifth rows and third column

21


In [165]:
ri[::3]

array([[10, 39, 12, 30, 28, 21, 23, 29, 28, 27],
       [11, 14, 21, 22, 19, 17, 19, 26, 25, 38],
       [27, 38, 14, 11, 13, 10, 19, 16, 17, 24],
       [18, 35, 30, 38, 26, 15, 20, 19, 35, 14]], dtype=int32)

In [166]:
ri[:,8]  # start left side

array([28, 16, 20, 25, 28, 24, 17, 29, 12, 35], dtype=int32)

In [167]:
ri[:,-5] # start right side

array([21, 14, 22, 17, 30, 26, 10, 29, 37, 15], dtype=int32)

In [168]:
ri[2:6,5:8] # row = 2:6 means (2-5) and column = 5:8 (5-7)

array([[22, 38, 30],
       [17, 19, 26],
       [30, 20, 32],
       [26, 34, 21]], dtype=int32)

In [169]:
ri

array([[10, 39, 12, 30, 28, 21, 23, 29, 28, 27],
       [27, 30, 25, 27, 13, 14, 11, 11, 16, 18],
       [32, 27, 35, 37, 28, 22, 38, 30, 20, 13],
       [11, 14, 21, 22, 19, 17, 19, 26, 25, 38],
       [32, 22, 28, 23, 32, 30, 20, 32, 28, 26],
       [19, 37, 34, 31, 26, 26, 34, 21, 24, 21],
       [27, 38, 14, 11, 13, 10, 19, 16, 17, 24],
       [38, 10, 31, 25, 38, 29, 37, 33, 29, 20],
       [34, 39, 32, 22, 13, 37, 27, 17, 12, 20],
       [18, 35, 30, 38, 26, 15, 20, 19, 35, 14]], dtype=int32)

In [170]:
ri[3:6,5:9]

array([[17, 19, 26, 25],
       [30, 20, 32, 28],
       [26, 34, 21, 24]], dtype=int32)

In [171]:
ri[0:3,0:3]

array([[10, 39, 12],
       [27, 30, 25],
       [32, 27, 35]], dtype=int32)

# Array Manipulation functions

In [172]:
# Reshape an Array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) # Reshape to 1 X 3
print("Reshape array:",reshaped)

Reshape array: [[1 2 3]]


In [173]:
# Reshape an Array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) # Reshape to 1 X 3
print("Reshape array:",reshaped)

Reshape array: [[1]
 [2]
 [3]]


In [174]:
# Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1) # Flatten to 1D array
print("Flattened Array:",flattened)

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10]


In [176]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


# Stacking
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be
stacked

In [182]:
# Horizontal stacking
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [183]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# using hstack for Horizontal stacking


In [185]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [186]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# using vstack for vertical stacking

In [188]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
its opposite of Stacking 

In [189]:
# Horizontal splitting
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [190]:
np.hsplit(w1,2) # splitting by 2

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [193]:
np.hsplit(w1,4) # splitting by 4


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [194]:
# Vertical splitting
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [195]:
np.vsplit(w2,3) # splittig into 3 rows

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# Mathematical Function

In [197]:
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [198]:
squared = np.power(g,2)
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [199]:
subtraction = np.subtract(g,1)
print("Subtraction of g:",subtraction)

Subtraction of g: [0 1 2 3]


In [201]:
a3 = np.array([4,5,6])
a4 = np.array([7,8,9])
dot_product = np.dot(a3,a4)
print("Dot product of a3 and a4 is:",dot_product)

Dot product of a3 and a4 is: 122


# Random Sampling Functions

In [203]:
# Generate random values 0 and 1
rand_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values:",rand_vals)

Random values: [0.92390691 0.97445132 0.53584974]


In [205]:
# Set seed for reproducibility
np.random.seed(0) 

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [206]:
# Generate random integer
rand_ints = np.random.randint(0,10, size=5)
print("Random Integer:",rand_ints)

Random Integer: [3 7 9 3 5]


In [207]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# Numpy masking or filter

In [208]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
id(mat)

1590811192240

In [210]:
len(mat)

10

In [213]:
mat.shape # print rows and column

(10, 10)

In [214]:
mat< 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [216]:
mat[mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [217]:
mat[mat <= 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [218]:
mat[mat == 50]

array([50])

In [219]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [220]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

 # Iterating


In [222]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
# Looping on 1D array
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [224]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
## Looping on 2D array
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [226]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [227]:
# Looping on 3D array
for i in p3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [228]:
# print all items in 3D using nditer ----> first convert in to 1D and applying Loop
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7


# 7. Boolean & Logical Functions

In [229]:
# Check if all element are true
# all
logical_test = np.array([True, True, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: True


In [231]:
# Check if all element are true it will print 'True' otherwise if one value false it will print 'False'
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print("All elements:",all_true)


All elements: False


In [232]:
logiacl_test = np.array([False, False, False])
all_false = np.all(logical_test)
print("All elements False:",all_false)

All elements False: False


#  Set Operations

In [233]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a , set_b)
print("Intersection of a and b is:",intersection)

Intersection of a and b is: [3 4]


In [234]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b is:",union)

Union of a and b is: [1 2 3 4 5 6]


# Speed of List Vs Numpy

# List

In [235]:
# Element-wise addition
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time 
start = time.time()
for i in range(len(a)):
    c.append( a[i] + b[i])

print(time.time()-start)    


5.03966498374939


# Numpy

In [236]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a + b
print(time.time()-start)

0.2601780891418457


so ,Numpy is Faster than Normal Python programming ,we can see in above Example.
because Numpy uses C type array


# Memory Used for List Vs Numpy


# List

In [239]:
p = [i for i in range(10000000)]
import sys
sys.getsizeof(p)

89095160

# Numpy

In [240]:
R = np.arange(10000000)
sys.getsizeof(R)

80000112

In [241]:
# we can decrease more in numpy
R = np.arange(10000000, dtype =np.int16)
sys.getsizeof(R)


20000112

# Advance Indexing and Slicing


In [242]:
# Normal Indexing and slicing
w = np.arange(12).reshape(4,3)
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [246]:
# Fetching 5 from array
print(w[1,2])

5


In [247]:
# Fetching 3, 4, 5, 6, 7, 8
w[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [248]:
w[1:3,1:3]

array([[4, 5],
       [7, 8]])

# Fancy Indexing
Fancy indexing allows you to select or modify specific elements based on complex conditions
or combinations of indices. It provides a powerful way to manipulate array data in NumPy.


In [249]:
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [251]:
# Fetch 1,3,4 row
w[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [252]:
z = np.arange(24).reshape(6,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [254]:
# Fetch 1, 3, 4, 6 rows
z[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [255]:
# Fetch 1,3,4 columns
z[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

# Matrix Multiplication



In [3]:
import numpy as np
A = np.array([[1,2],[3,4]])
res = np.dot(A,A)
print(res)

[[ 7 10]
 [15 22]]


In [4]:
import numpy as np
a = [[1, 2], [2, 3]]
b = [[4, 5], [6, 7]]

print("Matrix A:")
print(a)
print("Matrix B:")
print(b)

c = np.dot(a, b)
print("Result:")
print(c)

Matrix A:
[[1, 2], [2, 3]]
Matrix B:
[[4, 5], [6, 7]]
Result:
[[16 19]
 [26 31]]
